<?php

namespace Resi\GestionResiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaRepository extends EntityRepository{
    
    
    
    public function findByCodFactura($cod){
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('f.codFactura,f.fechaExpedicion,f.importe,f.fechaPago')
                    ->from('GestionResiBundle:Factura', 'f')
                    ->where('f.codFactura = :cod')
                    ->setParameter('cod', $cod)
                    ->getQuery()
                    ->getResult();
    }
    
    public function findAndUpdateByCodFactura($cod){ 
        $this->getEntityManager()
                    ->createQueryBuilder()
                    ->update('GestionResiBundle:Factura', 'f')
                    ->set('f.fechaPago',  'CURRENT_DATE()')
                    ->where('f.codFactura = :cod')
                    ->setParameter('cod', $cod)
                    ->getQuery()
                    ->execute();
        return $this->findByCodFactura($cod);
    }
    
    public function findFacturassByDNIResidente($dni)
    { 
        //Conseguimos el contrato
        $contratos = $this->getEntityManager()->getRepository("GestionResiBundle:Contrato")->findByUsuarioDNI($dni);
        //echo 'Ya tenemos los contraros';
        
        /*
        foreach($contratos as $c)
        {
                echo $c['CodContrato'];
        }
        */ 
        
        if($contratos == null)
        {
            //echo 'No hay contratos aún para este usuario';
        }
        else 
        {
            //echo 'Se han encontrado facturas';
            $facturas = array();
            foreach($contratos as $c)
            {
                $facturas = $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('f.codFactura,f.fechaExpedicion,f.importe,f.fechaPago')
                    ->from('GestionResiBundle:Factura', 'f')
                    ->where('f.codContrato = :cod')
                    ->setParameter('cod', $c['CodContrato'])
                    ->getQuery()
                    ->execute();
            }
            return $facturas;
        }
        return null;
    }
    
    public function findAllSinId(){
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('f.codFactura,f.fechaExpedicion,f.importe,f.fechaPago,con.CodHabitacion,u.nick,u.dNI')
                    ->from('GestionResiBundle:Factura', 'f')
                    ->join('GestionResiBundle:Contrato', 'con','WITH','f.codContrato=con.CodContrato')
                    ->join('GestionResiBundle:Usuario','u','WITH','u.dNI=con.DNIResidente')
                    ->getQuery()
                    ->getResult();
    }
    
    public function findFacturasByCodContrato($codContrato)
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('f.codFactura,f.fechaExpedicion,f.importe,f.fechaPago')
                    ->from('GestionResiBundle:Factura', 'f')
                    ->where('f.codContrato = :cod')
                    ->setParameter('cod', $codContrato)
                    ->getQuery()
                    ->execute();
    }
}
