<?php

namespace Resi\GestionResiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Resi\GestionResiBundle\Entity\Habitacion;

/**
 * usuarioadminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioadminRepository extends EntityRepository{
    
    public function findAdmin($dni){
        $dql=$this->getEntityManager()->createQueryBuilder()
                  ->select("a.idAdmin")
                  ->from("GestionResiBundle:usuarioadmin", "a")
                  ->where("a.dNIUser=:dni")
                  ->setParameter("dni", $dni)
                  ->getQuery()
                  ->getResult();
        if($dql!=null){
            return true;
        }else{
            return false;
        }
    }
    
    public function borraUser($dni){
    //Eliminamos la vida
        
        //Facturas
        $listaContratos = $this->getEntityManager()->getRepository('GestionResiBundle:Contrato')->findByUsuarioDNI($dni);
        //var_dump($listaContratos);
        
        foreach ($listaContratos as $c)
        {
            $this->getEntityManager()->createQueryBuilder()
             ->delete()
             ->from("GestionResiBundle:Factura","f")
             ->where("f.codContrato = :codC")
             ->setParameter("codC", $c['CodContrato'])
             ->getQuery()
             ->execute();
        }
        
        //Contratos
        $this->getEntityManager()->createQueryBuilder()
             ->delete()
             ->from("GestionResiBundle:Contrato","c")
             ->where("c.DNIResidente = :dni")
             ->setParameter("dni", $dni)
             ->getQuery()
             ->execute();
        
        //El usuario
        $this->getEntityManager()->createQueryBuilder()
             ->delete()
             ->from("GestionResiBundle:Usuario","u")
             ->where("u.dNI= :dni")
             ->setParameter("dni", $dni)
             ->getQuery()
             ->execute();
         
        
        
        //Hay que actualizar los contratos
        /*
        $this->getEntityManager()->createQueryBuilder()
             ->update("GestionResiBundle:Contrato","c")
             ->set('c.DNIResidente', '?1')
             ->where("c.DNIResidente = :dni")
             ->setParameter("dni", $dni)
             ->setParameter(1, "ANONYMOUS")
             ->getQuery()
             ->execute();
        
        
        $this->getEntityManager()->createQueryBuilder()
             ->update("GestionResiBundle:Usuario","u")
             ->set('u.dNI', '?1')
             ->where("u.dNI= :dni")
             ->setParameter("dni", $dni)
             ->setParameter(1, "ANONYMOUS")
             ->getQuery()
             ->execute();
         * 
         * 
         */
    }
    
    public function borraHabitacion($cod){
        $this->getEntityManager()->createQueryBuilder()
             ->delete()
             ->from("GestionResiBundle:Habitacion","h")
             ->where("h.CodHabitacion= :cod")
             ->setParameter("cod", $cod)
             ->getQuery()
             ->execute();
    }
    
    public function borrarFactura($cod){
        $this->getEntityManager()->createQueryBuilder()
             ->delete()
             ->from("GestionResiBundle:Factura","f")
             ->where("f.codFactura= :cod")
             ->setParameter("cod", $cod)
             ->getQuery()
             ->execute();
    }

        public function nuevaHabitacion($cod,$tipo,$desc,$tarifa){
        $habitacion=new Habitacion();
        $habitacion->setCodhabitacion($cod);
        $habitacion->setTipohabitacion($tipo);
        $habitacion->setDescripcion($desc);
        $habitacion->setTarifames($tarifa);
        $em=$this->getDoctrine()->getManager();
        $em->getRepository('GestionResiBundle:Habitacion');
        $em->persist($habitacion);
        $em->flush();
    }
    
}
